PSF/
    __init__.py
    fitness/
        __init__.py
        edge_difference.py
        similarity_rgb.py
        similarity_lab.py
    puzzle/
        __init__.py
        piece.py
        puzzle.py
    solver/
        __init__.py
        abstract_solver.py
        generic_solver.py
    util/
        __init__.py
        flatten_image.py
        inflate_immage.py
        piece_cache.py
